[package]
name = "db3"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.24"
tonic = "0.7.2"
bytes = "1"
async-trait = "0.1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["full"] }
prost = "0.10"
prost-types = "0.10"
log = "0.4.16"
uselog-rs = "0.3.0"
bincode = "1.1.4"
futures = "0.3.21"
futures-util = "0.3"
clap = { version = "3.1.8", features = ["derive"] }
arrow = { version = "16", features = ["prettyprint"] }
parquet = { version = "16", features = ["arrow"] }
crossbeam = "0.8.1"
chrono = { version = "0.4", default-features = false }
pretty_env_logger = "0.4.0"
# Note datafusion must use the same version with sqlparser
datafusion = {path = "./thirdparty/arrow-datafusion/datafusion/core", version="9.0.0"}
sqlparser = {path ="./thirdparty/arrow-datafusion/thirdparty/sqlparser-rs", version="0.17.0"}
timely = {path ="./thirdparty/timely-dataflow/timely", version="0.12.0"}
arc-swap = "1.5.0"
crossbeam-skiplist_piedb = "0.8.10"
msql-srv = { path = "./thirdparty/msql-srv"}
mysql = "22"
mysql_async = "0.30.0"
rust-s3 = {version="0.31", features=["tags", "tokio-native-tls", "blocking"]}
crc32c = "0.6"
tempdir = "0.3.5"
etcd-client = "0.9"
rand = "0.8.5"
regex = "1.5.5"
string-builder = "0.2.0"
pg_wire = { path = "./thirdparty/pg_wire", features = ["tokio_net"] }
shadow-rs = "0.11.0"
[[bin]]
name = "db3"
path = "src/cmd/db3.rs"


[build-dependencies]
tonic-build = "0.7.2"
shadow-rs = "0.11.0"

[dev-dependencies]
test-case = "2.0.2"
criterion = "0.3"
