[package]
name = "rtstore"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.22"
tonic = "0.7.2"
bytes = "1"
async-trait = "0.1.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.30"
tempfile = "3.3.0"
tokio = { version = "1.17.0", features = ["full"] }
prost = "0.10"
prost-types = "0.10"
log = "0.4.16"
uselog-rs = "0.3.0"
bincode = "1.1.4"
futures = "0.3"
clap = { version = "3.1.8", features = ["derive"] }
arrow = { version = "15", features = ["prettyprint"] }
parquet = { version = "15", features = ["arrow"] }
crossbeam = "0.8.1"
chrono = { version = "0.4", default-features = false }
pretty_env_logger = "0.4.0"
# Note datafusion must use the same version with sqlparser
datafusion = {git = "https://github.com/rtstore/arrow-datafusion.git", rev = "7288efc"}
sqlparser = {git = "https://github.com/rtstore/sqlparser-rs.git", rev = "22a6acf"}
arc-swap = "1.5.0"
crossbeam-skiplist_piedb = "0.8.10"
msql-srv = { git = "https://github.com/imotai/msql-srv", rev = "ee14d86" }
mysql = "22"
mysql_async = "0.29.0"
rust-s3 = {version="0.31", features=["tags", "tokio-native-tls", "blocking"]}
crc32c = "0.6"
tempdir = "0.3.5"
etcd-client = "0.9"
rand = "0.8.5"

[[bin]]
name = "rtstore"
path = "src/cmd/rtstore.rs"


[build-dependencies]
tonic-build = "0.7.2"

[dev-dependencies]
test-case = "2.0.2"
criterion = "0.3"
