name: Label PRs

on:
  pull_request:
    types: [opened, edited]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: pr-labeler
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.CR_PAT }}"
        configuration-path: .github/labels.yaml
        sync-labels: true
