name: Label PRs

on:
  pull_request:
    types: [opened, edited]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    name: pr-labeler
    steps:
    - uses: srvaroa/labeler@master
      env:
        GITHUB_TOKEN: "${{ secrets.CR_PAT }}"
        configuration-path: .github/labels.yaml
        sync-labels: true
